config/routes.rb
Rails.application.routes.draw do
  get "/posts/:post" => "posts#show"
  get "/:post" => "posts#show"
  root "posts#show", post: "home"

  get "/home" => "posts#show", as: "home"

  get "/my_first_post" => "posts#show", as: "my_first_post"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    if valid_post?
      render template: "posts/#{params[:post]}"
    else
      render file: "public/404.html", status: :not_found
    end
  end

  private
  def valid_post?
    File.exist?(Pathname.new(Rails.root + "app/views/posts/#{params[:post]}.html.erb"))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_navbar.html.erb
<header>
  <div class='navbar'>

    <nav>
      <ul>
      <li><%= link_to 'Home', home_path %></li>
      <li><%= link_to 'My First Post', my_first_post_path %></li>
      </ul>

    </nav>

  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mycoolblog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/posts/home.html.erb
<h1>Home page</h1>

app/views/posts/my_first_post.html.erb
<h1> This is my first post! </h1>